### PR TITLE
fix(typings): `unknown` typed as `unknown?`

### LINKED ISSUE #88: [BUG] `unknown` typed as `unknown?`
## Describe the bug
Using `unknown` results in `unknown?`:
image

## Reproduction
https://zap.redblox.dev/playground.html?code=ZXZlbnQgdmFsdWUgPSB7DQogICAgZnJvbTogU2VydmVyLA0KICAgIHR5cGU6IFJlbGlhYmxlLA0KICAgIGNhbGw6IFNpbmdsZVN5bmMsDQogICAgZGF0YTogdW5rbm93biwNCn0NCg==

### PR DESCRIPTION
**Pull request by sasial-dev**
Closes #88

### CODE REVIEW

File: zap/src/output/typescript/mod.rs [hunk 1]
```diff
@@ -112,6 +112,12 @@ pub trait Output {
 
 			Ty::Opt(ty) => {
 				self.push_ty(ty);
+
+				// do not allow the type to be "unknown?"
+				if let Ty::Unknown = **ty {
+					return;
+				}
+
 				self.push(" | undefined");
```
Comment (jackhexed) [inline zap/src/output/typescript/mod.rs]:
```suggestion
				if !matches!(**ty, Ty::Unknown) {
					self.push("| undefined");
				}
```

File: zap/src/output/luau/mod.rs [hunk 2]
```diff
@@ -106,8 +106,12 @@ pub trait Output {
...
 
 			Ty::Opt(ty) => {
-				self.push_ty(ty);
-				self.push("?");
+				if let Ty::Unknown = **ty {
+					self.push_ty(ty);
+				} else {
+					self.push_ty(ty);
+					self.push("?");
+				}
```
Comment (jackhexed) [inline zap/src/output/luau/mod.rs]:
```suggestion
				self.push_ty(ty);
				
				if !matches!(**ty, Ty::Unknown) {
					self.push("?");
				}
```

**Review by jackhexed — CHANGES_REQUESTED** [review]

**Review by jackhexed — APPROVED** [review]
lgtm
